name: Destroy Terraform Infrastructure

on:
  workflow_dispatch:  # Allows manual trigger for destruction

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub-Terraform-Role
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform Destroy
        run: terraform plan -destroy -out=tfplan

      - name: Apply Terraform Destroy
        run: terraform apply -auto-approve tfplan
