name: Destroy Specific Terraform Resources

on:
  workflow_dispatch:
    inputs:
      resources:
        description: "Comma-separated list of Terraform resources to destroy (e.g., aws_instance.example,aws_s3_bucket.mybucket)"
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub-Terraform-Role
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Parse Resources for Destruction
        id: parse_resources
        run: |
          RESOURCES_LIST=$(echo "${{ github.event.inputs.resources }}" | sed 's/,/ -target=/g')
          echo "TARGETS=-target=${RESOURCES_LIST}" >> $GITHUB_ENV

      - name: Plan Terraform Destroy
        run: terraform plan -destroy ${{ env.TARGETS }} -out=tfplan

      - name: Apply Terraform Destroy
        run: terraform apply -auto-approve tfplan
